### ISSUE TITLE
Monitoror doesn't seem to work

### ISSUE THREAD

**Issue by julien-langlois** [monitoror/monitoror#166]
Hi guys!

The demo on your website doesn't seem to work.

In the same way, I can't get Monitoror to run on my machine (Debian 64 bits) with the provided executable and default configuration. I get the same error as on your site using ?configPath mode. At the end I'm asked to check my configuration because it can't be loaded.

Did I miss a step?

**Comment by Alex-D** [comment]
Hi Julien,

First, thank you for your interest in our project.

Monitoror is ready to use, but it not released yet. It will be released very soon (in the next few days I hope) \o/

The doc and demo are ahead of the latest release since they are on config v5, and the current version is on config v3. That's why you cannot get it to work. You did not miss any step ^^

If you want to start using Monitoror today, you need to download it from [the latest build at this time](https://github.com/monitoror/monitoror/runs/455029946), via the Artifacts button in the top right corner.

Otherwise, wait for the release in the next hours/days :)

For the demo, this is a configuration issue that will be fixed by the #168

**Comment by julien-langlois** [comment]
Indeed it is functional with the last build, however I have the impression that the html of the tiles is not correctly rendered. 

That said, I'll wait for the future release so I can really get into it.

Good luck to you from a lillois ;)
