### ISSUE TITLE
Default configuration files

### ISSUE THREAD

**Issue by mvaldes14** [monitoror/monitoror#220]
1. It would be nice that the first time you run the program it generates the default .env files as well as the sample config.json in the location where the binary/exe is.
2. The program should be default try to open http://localhost:8080/?configPath=./config.json

**Comment by Alex-D** [comment]
I agree with the first point, but not at the runtime. Maybe a command like `monitoror init` to prevent creating useless files for those who do not want them since you can put your env variables in your profile, or in the command line and use a config from a URL.

I'm OK with the 2nd idea, but not that way. I think it can be done via another idea from another issue/post (IDK where ^^') which consists in setting default config path/URL from `.env`, which makes the query param useless, and the usage more transparent and easy.

Thank you for your feedback :)
