### ISSUE TITLE
Add theme customization

### ISSUE THREAD

**Issue by Archerfy** [monitoror/monitoror#320]
Add the option to edit the page to your own touch.

Able to change colors
Able to change background
Able to change font, font-size, icons

Able to add more color and own options.
Example set in config.json as option under-maintenance: yes and it will say under maintenance on the page with a different color

**Comment by Alex-D** [comment]
Hi!

First, your issue is just a list of ideas. Each feature should have its own issue.


## Colors / Background color

Why not. I've made the design based on CSS custom properties.

For now: fork, edit index.html with your own values, and build your own customized version.


## Fonts

Why did you want to change font-family?
I think we can open font used via custom properties too. For now, that's not the case.


## Font size

Prefer to use the [config `zoom` option](https://monitoror.com/documentation/#ui-configuration).


## Icons

Why did you want to change existing icons? I need more details to understand the need here.


## New states

That's not that simple to support "new colors". That's not just colors. It's all about *states*. So, what's the point of an "under maintenance" state? This is a non-sense to put that in the config.json. If you edit config.json, just add an empty tile as a placeholder... but why just not keep it in red if it's down? Even if you know why it's down: it's down. So the real state of your service is: not working, so that's just red ^^


## New options

What are "new options"? Without any detail, it's hard to respond to that.

Maybe you are asking for more tile types, so please be sure to check #253 and #285 and https://github.com/monitoror/monitoror/issues/286#issuecomment-603242364

-----

As you can see, you just drop some lines, but there are a lot of blurry requests in your issue.

When I get more details from you, I will split that into as many issues as the features requested.

**Comment by Archerfy** [comment]
Hello,

For colors and background I guess making my own version will work for now.
Same for the font. I didn't know about the font-size with zoom option, sorry for that.

For the icons. IIt is not a important feature, But maybe animated icons. (I just like animated icons.)

New states and new options. I think I didn't read the documentation enough. 
There are tiles types that I need already in monitoror. So sorry for my lack on reading the documentation better.

If the customization with colors and background could be implemented in the future would be awesome.
But also it is not a priority if I am able to fork it myself.
The others are not really needed anymore (my lack on reading documentation)
And the icons, mwah. I don't think we would look aat the page 24/7 with our eyes.

Sorry for some misunderstanding, and sorry for my lack on reading the documentation.
Thank youu for your help.

**Comment by Alex-D** [comment]
Monitoror is optimized to work on very small CPU/GPU like a Raspberry Pi, without burning it ^^ Adding animated icons is not really a good thing, and it adds noise to a wall which can already be really heavy.

So, I will consider this issue as "Allow theme customization" only :)

**Comment by Alex-D** [comment]
To keep thing clean, I've created a more focused issue here: #321
